/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compute SHA256 hash of a file's contents
 * Returns empty string if file cannot be read
 */
export declare function computeFileHash(filePath: string): string;
/**
 * Compute SHA256 hashes for multiple files in parallel
 * Returns a map of file path to hash
 */
export declare function computeFileHashesParallel(
  filePaths: Array<string>
): Record<string, string>;
/**
 * Find files matching glob patterns in a directory, respecting gitignore
 * Returns absolute file paths
 */
export declare function findFilesWithGlob(
  rootDir: string,
  patterns: Array<string>
): Array<string>;
/**
 * Find directories containing marker files or directories (e.g., mix.exs, Cargo.toml, *.xcodeproj)
 * Returns absolute directory paths
 */
export declare function findDirectoriesWithMarkers(
  rootDir: string,
  markers: Array<string>
): Array<string>;
/**
 * Build a manifest of file hashes for given files
 * Returns a map of relative path to hash
 */
export declare function buildManifest(
  files: Array<string>,
  rootDir: string
): Record<string, string>;
/**
 * Check if any files have changed compared to a cached manifest
 * Returns true if changes detected, false if no changes
 * Uses streaming with early exit on first change
 */
export declare function hasChanges(
  rootDir: string,
  patterns: Array<string>,
  cachedManifest: Record<string, string>
): boolean;
/**
 * Combined function: find files, build manifest, and optionally check for changes
 * Returns (has_changes: bool, manifest: HashMap) for efficiency
 */
export interface CheckResult {
  hasChanges: boolean;
  manifest: Record<string, string>;
  files: Array<string>;
}
/** Efficiently check for changes and build manifest in one pass */
export declare function checkAndBuildManifest(
  rootDir: string,
  patterns: Array<string>,
  cachedManifest?: Record<string, string> | undefined | null
): CheckResult;
/** A document record for FTS indexing */
export interface FtsDocument {
  /** Unique identifier for the document */
  id: string;
  /** The text content to index */
  content: string;
  /** Optional metadata as JSON string */
  metadata?: string;
}
/** A search result from FTS query */
export interface FtsSearchResult {
  /** Document ID */
  id: string;
  /** The matched content */
  content: string;
  /** Optional metadata as JSON string */
  metadata?: string;
  /** BM25 relevance score */
  score: number;
}
/**
 * Initialize or open an FTS index at the given path
 * Creates the table if it doesn't exist
 */
export declare function ftsInit(
  dbPath: string,
  tableName: string
): Promise<boolean>;
/**
 * Index documents for FTS
 * Adds documents to the table and creates/updates the FTS index
 */
export declare function ftsIndex(
  dbPath: string,
  tableName: string,
  documents: Array<FtsDocument>
): Promise<number>;
/** Search documents using FTS (BM25) */
export declare function ftsSearch(
  dbPath: string,
  tableName: string,
  query: string,
  limit?: number | undefined | null
): Promise<Array<FtsSearchResult>>;
/** Delete documents by ID from the FTS index */
export declare function ftsDelete(
  dbPath: string,
  tableName: string,
  ids: Array<string>
): Promise<number>;
/**
 * Generate embeddings for a list of texts
 * Returns a 2D array of embeddings (one per text)
 */
export declare function generateEmbeddings(
  texts: Array<string>
): Array<Array<number>>;
/**
 * Generate embedding for a single text
 * Returns a 1D array (the embedding vector)
 */
export declare function generateEmbedding(text: string): Array<number>;
/** Get the embedding dimension (384 for all-MiniLM-L6-v2) */
export declare function getEmbeddingDimension(): number;
