/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A document record for FTS indexing */
export interface FtsDocument {
  /** Unique identifier for the document */
  id: string;
  /** The text content to index */
  content: string;
  /** Optional metadata as JSON string */
  metadata?: string;
}
/** A search result from FTS query */
export interface FtsSearchResult {
  /** Document ID */
  id: string;
  /** The matched content */
  content: string;
  /** Optional metadata as JSON string */
  metadata?: string;
  /** BM25 relevance score */
  score: number;
}
/** A search result from vector query */
export interface VectorSearchResult {
  /** Document ID */
  id: string;
  /** The matched content */
  content: string;
  /** Optional metadata as JSON string */
  metadata?: string;
  /** Similarity score (higher is more similar) */
  score: number;
}
/**
 * Compute SHA256 hash of a file's contents
 * Returns empty string if file cannot be read
 */
export declare function computeFileHash(filePath: string): string;
/**
 * Compute SHA256 hashes for multiple files in parallel
 * Returns a map of file path to hash
 */
export declare function computeFileHashesParallel(
  filePaths: Array<string>
): Record<string, string>;
/**
 * Find files matching glob patterns in a directory, respecting gitignore
 * Returns absolute file paths
 */
export declare function findFilesWithGlob(
  rootDir: string,
  patterns: Array<string>
): Array<string>;
/**
 * Find directories containing marker files or directories
 * Returns absolute directory paths
 */
export declare function findDirectoriesWithMarkers(
  rootDir: string,
  markers: Array<string>
): Array<string>;
/** Build a manifest of file hashes for given files */
export declare function buildManifest(
  files: Array<string>,
  rootDir: string
): Record<string, string>;
/** Check if any files have changed compared to a cached manifest */
export declare function hasChanges(
  rootDir: string,
  patterns: Array<string>,
  cachedManifest: Record<string, string>
): boolean;
export interface CheckResult {
  hasChanges: boolean;
  manifest: Record<string, string>;
  files: Array<string>;
}
/** Efficiently check for changes and build manifest in one pass */
export declare function checkAndBuildManifest(
  rootDir: string,
  patterns: Array<string>,
  cachedManifest?: Record<string, string> | undefined | null
): CheckResult;
/** Initialize or open a database at the given path */
export declare function dbInit(dbPath: string): Promise<boolean>;
/** Index documents for FTS */
export declare function ftsIndex(
  dbPath: string,
  tableName: string,
  documents: Array<FtsDocument>
): Promise<number>;
/** Search documents using FTS (BM25) */
export declare function ftsSearch(
  dbPath: string,
  tableName: string,
  query: string,
  limit?: number | undefined | null
): Promise<Array<FtsSearchResult>>;
/** Delete documents by ID */
export declare function ftsDelete(
  dbPath: string,
  tableName: string,
  ids: Array<string>
): Promise<number>;
/** Input for vector document indexing (napi-compatible) */
export interface VectorDocumentInput {
  id: string;
  content: string;
  vector: Array<number>;
  metadata?: string;
}
/** Index documents with vectors */
export declare function vectorIndex(
  dbPath: string,
  tableName: string,
  documents: Array<VectorDocumentInput>
): Promise<number>;
/** Search documents using vector similarity */
export declare function vectorSearch(
  dbPath: string,
  tableName: string,
  queryVector: Array<number>,
  limit?: number | undefined | null
): Promise<Array<VectorSearchResult>>;
/** Check if ONNX Runtime is available (downloaded) */
export declare function embeddingIsAvailable(): Promise<boolean>;
/**
 * Ensure ONNX Runtime and model are downloaded
 * Returns path to the ONNX Runtime library
 */
export declare function embeddingEnsureAvailable(): Promise<string>;
/** Generate embeddings for a list of texts */
export declare function generateEmbeddings(
  texts: Array<string>
): Promise<Array<Array<number>>>;
/** Generate embedding for a single text */
export declare function generateEmbedding(text: string): Promise<Array<number>>;
/** Get the embedding dimension (384 for all-MiniLM-L6-v2) */
export declare function getEmbeddingDimension(): number;
